name: ExtractBlocksAsImages
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" 
jobs:
  extract_blocks:
    runs-on: ubuntu-latest
    env:
      REMID: ${{ secrets.REMID }}
      SID: ${{ secrets.SID }}
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  
      - name: Update Sources list
        run: sudo apt update
      - name: Remove Chrome
        run: sudo apt purge google-chrome-stable
      - name: Install Chromium
        run: sudo apt install -y chromium-browser
      - name: Install all necessary packages
        run: pip install -r scripts/portal_blocks_extractor/requirements.txt
      - name: Run the scraping script
        run: python scripts/portal_blocks_extractor/script.py
      - name: Commit and push changes
        run: |
          git fetch --prune --unshallow
          git add .
          git diff
          git config --global user.email "ranger@bfportal.gg"
          git config --global user.name "Ranger"
          git commit -m "Updated blocks images" -a || echo "No changes to commit"
          git push 
